#!/bin/sh
# Return the current version
SELF="mvnw"
test -n "$MVNW_DEBUG" && set -x
# Initial checks
mvnw-check-commands

MVN_OUTPUT=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version`
if test -n "$(echo $MVN_OUTPUT | grep 'No POM')"; then
    echo "$SELF: No Pom here, aborting..."
    exit 1
fi
